{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ournezt.postgres.fullname" . }}
  labels:
    {{- include "ournezt.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ournezt.name" . }}-postgres
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "ournezt.postgres.selectorLabels" . | nindent 4 }}
{{- end }}
