{{- if and .Values.postgres.enabled (not .Values.postgres.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ournezt.postgres.fullname" . }}
  labels:
    {{- include "ournezt.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ournezt.name" . }}-postgres
type: Opaque
stringData:
  {{ .Values.postgres.auth.passwordKey }}: {{ .Values.postgres.auth.password | quote }}
{{- end }}
{{- if and .Values.core.enabled .Values.core.bootstrap.enabled (not .Values.core.bootstrap.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ournezt.core.fullname" . }}-bootstrap
  labels:
    {{- include "ournezt.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ournezt.name" . }}-core
type: Opaque
stringData:
  {{ .Values.core.bootstrap.passwordKey }}: {{ .Values.core.bootstrap.adminPassword | quote }}
{{- end }}
